import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/nabvar";
import Footer from "@/components/footer/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=''
      >
        <div className="flex flex-col min-h-screen">
          <div className="">
            <Navbar/>
          </div>
          <main className="pt-10 flex-grow bg-indigo-100">
            {children}
          </main>

          <div>
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
